name: CI

on: 
  pull_request: 
    branches: [ master ]  
  push: 
    branches: [ master ]
    
    
jobs:   
  test:   
    runs-on: ubuntu-latest 
    steps: 
    - name: Super-Linter
      uses: github/super-linter@v4.10.1

      


  deploy: 
    runs-on: self-hosted 
    steps: 
      #- uses: actions/checkout@v2  #this is used for if you want to push all source code into runner       
      - name: update code base 
        working-directory: /test_pipe/www/html 
        run: sudo git pull origin master        
      - name: restart   
        working-directory: /test_pipe/www/html
        run: sudo systemctl restart nginx  
      - name: yolo  
        working-directory: /test_pipe/www/html
        run: echo "$(pwd)"  
        
      
      
      
      
      
