name: CI

on: 
  pull_request: 
    branches: [ master ]  
  push: 
    branches: [ master ]
    
    
jobs: 
  deploy: 
    runs-on: self-hosted 
    steps: 
      #- uses: actions/checkout@v2  #this is used for if you want to push all source code into runner     
      - run: cd /test_pipe/www/html   
      - run: touch hello.txt
      - run: sudo git add .  
      - run: sudo git commit --all -m "yup here we go"  
      - run: sudo git push origin master
      - run: sudo systemctl restart nginx    
      
      
      
