name: CI

on: 
  pull_request: 
    branches: [ master ]  
  push: 
    branches: [ master ]
    
    
jobs: 
  first_one: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2       
      - run: echo "Hello there" 
      
